[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "lingxi"
author = "youngquan"
author-email = "youngquan@qq.com"
classifiers = ["License :: OSI Approved :: MIT License"]

description-file = "README.md"
requires-python = ">=3.6"